[project]
name = "tour-aggregator"
version = "0.1.0"
description = "Backend service for tourist routes aggregator"
authors = [
    { name = "Denis" }
]
readme = "README.md"
requires-python = ">=3.11"

dependencies = [
    "fastapi",
    "uvicorn",
    "sqlalchemy",
    "psycopg2-binary",
    "python-dotenv",
    "python-jose",
    "passlib[bcrypt]",
    "pytest"
]

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests"]

[tool.black]
line-length = 88

[tool.isort]
profile = "black"